---
title: "Intensity analysis"
output:
  html_document:
    df_print: paged
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
---

# Choose Path and File
```{r}
#################################
##        Variables            ##
##                             ##
##    Path                     ##
##    File                     ##
##                             ##
#################################

Path1='C:/Users/m/Desktop/GCaMP_CogRx/'
File1="All_Experiments_BaseTreat.csv"

Path2='C:/Users/m/Desktop/GCaMP_CogRx/'
File2="All_Experiments_Ratios.csv"

```

# Required libraries
```{r}

library(readr)
library(plyr)
library(forcats)
library(lme4)
library(ggplot2)
library(stargazer)
library(lmerTest)
library(rcompanion)
library(dplyr)
library(tidyverse)
library(emmeans)
library(reshape2)
library(tidyr)
library(qwraps2)
library(arsenal)
library(table1)
library(plotrix)
library(ggResidpanel)
library(corrplot)
library(data.table)

#install.packages("corrplot")
#source("http://www.sthda.com/upload/rquery_cormat.r")

#install.packages("GGally")
#source("https://raw.githubusercontent.com/briatte/ggcorr/master/ggcorr.R")


```

# Set working directory (for .rmd scripts)
```{r setup}

knitr::opts_knit$set(root.dir = Path1)

```

# Load File
```{r}

Absolute <- read_csv(file.path(Path1,File1), col_types = cols (Case = 'f'))

Ratios <- read_csv(file.path(Path2,File2), col_types = cols (Case = 'f'))

```



# STATS

## Absolute Intensities Baseline and Treated

### 1.Max intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Max_Intensity~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Transform to improve data
Absolute$Max_Intensity_ratio_tukey <- transformTukey(Absolute$Max_Intensity)
ME_peak_number2<- lmer(Max_Intensity_ratio_tukey~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Boxplot
Absolute %>%
  ggplot( aes(x=Abeta, y=Max_Intensity, fill=Treatment)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Drug)

# Boxplot
Absolute %>%
  ggplot( aes(x=Drug, y=Max_Intensity, fill=Abeta)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Treatment)

```



### 2.Mean intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Mean_Intensity~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Transform to improve data
Absolute$Mean_Intensity_ratio_tukey <- transformTukey(Absolute$Mean_Intensity)
ME_peak_number2<- lmer(Mean_Intensity_ratio_tukey~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Boxplot
Absolute %>%
  ggplot( aes(x=Abeta, y=Mean_Intensity, fill=Treatment)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Drug)

# Boxplot
Absolute %>%
  ggplot( aes(x=Drug, y=Mean_Intensity, fill=Abeta)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Treatment)


```


### 3.Min intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Min_Intensity~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Transform to improve data
Absolute$Min_Intensity_ratio_tukey <- transformTukey(Absolute$Min_Intensity)
ME_peak_number2<- lmer(Min_Intensity_ratio_tukey~Abeta*Drug*Treatment+(1|Case)+(1|Experiment),data = Absolute)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug*Treatment, adjust="tukey")

# Boxplot
Absolute %>%
  ggplot( aes(x=Abeta, y=Min_Intensity, fill=Treatment)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Drug)

# Boxplot
Absolute %>%
  ggplot( aes(x=Drug, y=Min_Intensity, fill=Abeta)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)+
  facet_wrap(~  Treatment)

    
```


## Ratio Treatment/Baseline
### 1.Max intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Max_Intensity_ratio~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Transform to improve data
Ratios$Max_Intensity_ratio_tukey <- transformTukey(Ratios$Max_Intensity_ratio)
ME_peak_number2<- lmer(Max_Intensity_ratio_tukey~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Boxplot
Ratios %>%
  ggplot( aes(x=Abeta, y=Max_Intensity_ratio, fill=Drug)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)

    
```

### 2.Mean intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Mean_Intensity_ratio~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Transform to improve data
Ratios$Mean_Intensity_ratio_tukey <- transformTukey(Ratios$Mean_Intensity_ratio)
ME_peak_number2<- lmer(Mean_Intensity_ratio_tukey~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Boxplot
Ratios %>%
  ggplot( aes(x=Abeta, y=Mean_Intensity_ratio, fill=Drug)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)

    
```


### 3.Min intensity
```{r}
                                  
# Linear model + posthoc
ME_peak_number2<- lmer(Min_Intensity_ratio~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Transform to improve data
Ratios$Min_Intensity_ratio_tukey <- transformTukey(Ratios$Min_Intensity_ratio)
ME_peak_number2<- lmer(Min_Intensity_ratio_tukey~Abeta*Drug+(1|Case)+(1|Experiment),data = Ratios)
summary(ME_peak_number2)
resid_panel(ME_peak_number2)
anova(ME_peak_number2)
emmeans(ME_peak_number2, pairwise ~ Abeta*Drug, adjust="tukey")

# Boxplot
Ratios %>%
  ggplot( aes(x=Abeta, y=Min_Intensity_ratio, fill=Drug)) +
  geom_boxplot() +
  geom_boxplot(outlier.size = -1, width=0.75)

    
```




    

